# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: phone_book.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'phone_book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10phone_book.proto\"r\n\tPhoneBook\x12\x31\n\x0c\x63ontact_info\x18\x01 \x03(\x0b\x32\x1b.PhoneBook.ContactInfoEntry\x1a\x32\n\x10\x43ontactInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'phone_book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PHONEBOOK_CONTACTINFOENTRY']._loaded_options = None
  _globals['_PHONEBOOK_CONTACTINFOENTRY']._serialized_options = b'8\001'
  _globals['_PHONEBOOK']._serialized_start=20
  _globals['_PHONEBOOK']._serialized_end=134
  _globals['_PHONEBOOK_CONTACTINFOENTRY']._serialized_start=84
  _globals['_PHONEBOOK_CONTACTINFOENTRY']._serialized_end=134
# @@protoc_insertion_point(module_scope)
