# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\"\x81\x01\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x04\x12*\n\x0cproduct_type\x18\x02 \x01(\x0e\x32\x14.Product.ProductType\">\n\x0bProductType\x12\x0e\n\nUNSPECFIED\x10\x00\x12\x08\n\x04TIES\x10\x01\x12\n\n\x06SHIRTS\x10\x02\x12\t\n\x05SHOES\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCT']._serialized_start=18
  _globals['_PRODUCT']._serialized_end=147
  _globals['_PRODUCT_PRODUCTTYPE']._serialized_start=85
  _globals['_PRODUCT_PRODUCTTYPE']._serialized_end=147
# @@protoc_insertion_point(module_scope)
