# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sameLevel.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'sameLevel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsameLevel.proto\"4\n\x05Video\x12\x1e\n\nvideo_type\x18\x01 \x01(\x0e\x32\n.Videotype\x12\x0b\n\x03url\x18\x02 \x01(\t\"\x17\n\x07\x41rticle\x12\x0c\n\x04text\x18\x01 \x01(\t\"K\n\x0b\x43ontentType\x12\x17\n\x05video\x18\x01 \x01(\x0b\x32\x06.VideoH\x00\x12\x1b\n\x07\x61rticle\x18\x02 \x01(\x0b\x32\x08.ArticleH\x00\x42\x06\n\x04type\"-\n\x07Lecture\x12\"\n\x0c\x63ontent_type\x18\x01 \x01(\x0b\x32\x0c.ContentType\"\x88\x01\n\x06\x43ourse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61uthors\x18\x02 \x03(\t\x12%\n\x07lecture\x18\x03 \x03(\x0b\x32\x14.Course.LectureEntry\x1a\x38\n\x0cLectureEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\x05value\x18\x02 \x01(\x0b\x32\x08.Lecture:\x02\x38\x01*@\n\tVideotype\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03MP4\x10\x01\x12\x07\n\x03MOV\x10\x02\x12\x14\n\x10UNSUPPORTED_TYPE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sameLevel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COURSE_LECTUREENTRY']._loaded_options = None
  _globals['_COURSE_LECTUREENTRY']._serialized_options = b'8\001'
  _globals['_VIDEOTYPE']._serialized_start=361
  _globals['_VIDEOTYPE']._serialized_end=425
  _globals['_VIDEO']._serialized_start=19
  _globals['_VIDEO']._serialized_end=71
  _globals['_ARTICLE']._serialized_start=73
  _globals['_ARTICLE']._serialized_end=96
  _globals['_CONTENTTYPE']._serialized_start=98
  _globals['_CONTENTTYPE']._serialized_end=173
  _globals['_LECTURE']._serialized_start=175
  _globals['_LECTURE']._serialized_end=220
  _globals['_COURSE']._serialized_start=223
  _globals['_COURSE']._serialized_end=359
  _globals['_COURSE_LECTUREENTRY']._serialized_start=303
  _globals['_COURSE_LECTUREENTRY']._serialized_end=359
# @@protoc_insertion_point(module_scope)
